### ISSUE TITLE
framework could not be invoked 

### ISSUE THREAD

**Issue by keven-one** [Luka-M/unity-in-framework#1]
![1](https://user-images.githubusercontent.com/9433531/56880247-86bdd980-6a8e-11e9-857b-b05bc3789061.jpg)
I found that exporting the framework to another project could not be invoked correctly

**Comment by keven-one** [comment]
I solved it myself

**Comment by WyattMufson** [comment]
@FateOfKing not putting the solution to the problem is such a bad practice, wow
